name: recipe_collector
description: Collect your favorite recipes!
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  bloc: ^7.1.0
  flutter_bloc: ^7.2.0

  provider: ^6.0.0
  
  built_value: ^8.1.2
  built_collection: ^5.1.1

  dartz: ^0.10.0
  equatable: ^2.0.3
  uuid: ^3.0.4
  time: ^2.0.0

  sqlbrite: ^2.1.0
  flutter_styled_toast: ^2.0.0
  sliding_sheet: ^0.5.0
  image_picker: ^0.8.4+2
  duration_picker: ^1.0.1
  duration: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  build_runner:
  built_value_generator:

flutter:
  uses-material-design: true
